services:
  db:

    # connection url format : postgres://user:password@host:port/db

    # default user          : postgres
    # default db            : postgres (same as user)
    # connection url        : postgres://postgres:12345678@localhost:5432/postgres

    container_name: postgres-db

    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=12345678
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432

volumes:
  db-data:
