// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as AppIndexImport } from './routes/app/index'
import { Route as AppDashboardImport } from './routes/app/dashboard'
import { Route as AppLinksIndexImport } from './routes/app/links/index'

// Create Virtual Routes

const AboutIndexLazyImport = createFileRoute('/about/')()

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const AboutIndexLazyRoute = AboutIndexLazyImport.update({
  path: '/about/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about/index.lazy').then((d) => d.Route))

const LoginIndexRoute = LoginIndexImport.update({
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  path: '/app/',
  getParentRoute: () => rootRoute,
} as any)

const AppDashboardRoute = AppDashboardImport.update({
  path: '/app/dashboard',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/app/dashboard.lazy').then((d) => d.Route))

const AppLinksIndexRoute = AppLinksIndexImport.update({
  path: '/app/links/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/app/links/index.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/app/dashboard': {
      preLoaderRoute: typeof AppDashboardImport
      parentRoute: typeof rootRoute
    }
    '/app/': {
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/about/': {
      preLoaderRoute: typeof AboutIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/app/links/': {
      preLoaderRoute: typeof AppLinksIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AppDashboardRoute,
  AppIndexRoute,
  LoginIndexRoute,
  AboutIndexLazyRoute,
  AppLinksIndexRoute,
])
